### ISSUE TITLE
Success test

### ISSUE THREAD

**Issue by DavidBruant** [thom4parisot/elevato.rs#3]
For a given scenario, run the user's strategy and assert whether they succeeded to fulfill all requests. Tell the time they took (so they can notice improvement).

**Comment by DavidBruant** [comment]
In order for the player to understand the floor requests, it'd be nice to have a visual indication.
Idea: a light at each floor. Turn off the light when an elevator services the request.

**Comment by thom4parisot** [comment]
As we now use animationframe, it's doable to time every scenario completion very easily.
